import "./globals.css";
import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import { UserAuthContextProvider } from "../context/UserAuthContext";
import { Providers } from "@/providers/Providers";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Notification from "@/components/Notification/Notification";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {" "}
      {/* <Script
        strategy="lazyOnload"
        src="https://embed.tawk.to/655c8b38d600b968d3156e61/1hfonvl7i"
      /> */}
      <body className={inter.className}>
        <Providers>
          <ToastContainer
            position="bottom-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}

          <Notification />
        </Providers>
      </body>
    </html>
  );
}
